import './globals.css'
import Navbar from '@/components/Navbar'
import About from '@/components/About'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Navbar />
                <div> {children}</div>
                <About />
            </body>
        </html>
    )
}
